language: cpp

sudo: required
dist: bionic
services: docker

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

env:
 - FS_BACKEND=ON DOCKERFILE=archlinux
 - FS_BACKEND=OFF DOCKERFILE=archlinux
 - FS_BACKEND=ON DOCKERFILE=ub1804
 - FS_BACKEND=OFF DOCKERFILE=ub1804

matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os: osx
      env: FS_BACKEND=ON DOCKERFILE=ub1804
    - os: osx
      env: FS_BACKEND=OFF DOCKERFILE=ub1804

addons:
  apt:
    update: true
    packages:
      - lcov
  homebrew:
    packages:
      - cmake
      - boost
      - cppunit
      - hdf5
      - yaml-cpp
    update: true

before_cache:
  - brew cleanup

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

before_install:
  - if [[ "$CXX" == "gcc" ]];
    then
       export CC=gcc;
       export CXX=g++;
       export GCOV=gcov;
       export CTEST_ARGS=-V;
    else
       export CC=clang;
       export CXX=clang++;
       export GCOV=gcov;
       export CTEST_ARGS=-VV;
    fi

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ];
    then
      ./contrib/make-env.sh /tmp/docker.env;
      docker build -f ./dockerfiles/${DOCKERFILE}.Dockerfile . -t local/nixio;
      docker run --env-file /tmp/docker.env -d -i -t -v $(pwd):/src --name nixbuilder local/nixio;
      docker exec nixbuilder ${CXX} --version;
    fi

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ];
    then
      docker exec nixbuilder ctest ${CTEST_ARGS} --output-on-failure -S .travis.ctest;
    else
      $CXX --version;
      ctest ${CTEST_ARGS} --output-on-failure -S .travis.ctest;
    fi

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$FS_BACKEND" == "OFF" ]]; then
      docker cp nixbuilder:coverage.info ./converage.info;
      lcov -q --capture --directory . --no-extern --output-file coverage.info;
      bash <(curl -s https://codecov.io/bash) -f coverage.info -Z;
    fi

notifications:
  irc: "chat.freenode.net#gnode"
