language: cpp

sudo: required
dist: bionic

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

env:
 - FS_BACKEND=ON
 - FS_BACKEND=OFF

matrix:
  exclude:
    - os: osx
      compiler: gcc

addons:
  apt:
    update: true
    packages:
      - cmake
      - bash
      - cmake
      - clang-7
      - curl
      - doxygen
      - git
      - gcc-8
      - g++-8
      - libcppunit-dev
      - libboost-all-dev
      - libhdf5-dev
      - libhdf5-serial-dev
      - libyaml-cpp-dev
      - libstdc++-8-dev
      - lcov
      - valgrind
  homebrew:
    packages:
      - cmake
      - boost
      - cppunit
      - hdf5
      - yaml-cpp
    update: true

before_cache:
  - brew cleanup

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

before_install:
  - if [[ "$CXX" == "g++" ]];
    then
       export CTEST_ARGS=-V;
    else
       export CTEST_ARGS=-VV;
    fi
  - if [ "$CXX" == "g++" ]; then
    g++ --version;
    else clang --version;
    fi

script:
  - ctest ${CTEST_ARGS} --output-on-failure -S .travis.ctest

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$FS_BACKEND" == "OFF" ]]; then
      lcov -q --capture --directory . --no-extern --output-file coverage.info;
      bash <(curl -s https://codecov.io/bash) -f coverage.info -Z;
    fi

notifications:
  irc: "chat.freenode.net#gnode"
