language: cpp
env:
  matrix:
    - COMPILER=g++-4.8 CTEST_ARGS=-V
    - COMPILER=clang CXXFLAGS="-stdlib=libstdc++ -Qunused-arguments" CTEST_ARGS=-VV

script:
- CXX=${COMPILER} ctest ${CTEST_ARGS} --output-on-failure -S .travis.ctest

before_install:
  - if [[ "$COMPILER" == "g++-4.8" ]]; then sudo pip install cpp-coveralls; fi

install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo add-apt-repository ppa:boost-latest/ppa -y
- sudo add-apt-repository ppa:gnode/pandora -y
- sudo apt-get update -qq -y
- sudo apt-get install -q gcc-4.8 g++-4.8 libstdc++-4.8-dev libcppunit-dev libboost1.54-all-dev libhdf5-serial-dev libhdf5-dev libhdf5-7 valgrind cmake

after_success:
  - if [[ "$COMPILER" == "g++-4.8" ]]; then coveralls -b build --exclude test --exclude tmp --gcov gcov-4.8 --gcov-options '\-lp' > /dev/null ; fi

notifications:
  irc: "chat.freenode.net#gnode"