language: cpp

sudo: required
dist: xenial

services:
  - docker

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

env:
 - FS_BACKEND=ON
 - FS_BACKEND=OFF

matrix:
  exclude:
    - os: osx
      compiler: gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ];
    then
       export CC=clang;
       export CXX=clang++;
       export CTEST_ARGS=-VV;
    elif [[ "$CXX" == "g++" ]];
    then
       export CC=gcc-8;
       export CXX=g++-8;
       export CTEST_ARGS=-V;
    else
       export CC=clang-7;
       export CXX=clang++-7;
       export CTEST_ARGS=-VV;
    fi

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ];
    then
      ./contrib/make-env.sh /tmp/docker.env;
      docker build -t nix-ub1804 -f ./contrib/Dockerfile-ub1804 .;
    elif [ "$TRAVIS_OS_NAME" == "osx" ];
    then
      brew update;
      brew install cmake boost cppunit hdf5 yaml-cpp;
      brew --env;
    fi

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ];
    then
      docker run --env-file /tmp/docker.env -e -t -v `pwd`:/src nix-ub1804 /bin/bash -c "ctest ${CTEST_ARGS} --output-on-failure -S .travis.ctest;";
    else
      $CXX --version;
      ctest ${CTEST_ARGS} --output-on-failure -S .travis.ctest;
    fi

after_success:
  - if [[ "$COMPILER" == "g++" ]]; then
    coveralls -b build -E ".*CMakeFiles.*" -e cli -e test -e tmp --gcov gcov-4.8 --gcov-options '\-lp' > /dev/null;
    fi

notifications:
  irc: "chat.freenode.net#gnode"
