language: cpp

sudo: required
dist: bionic
services: docker

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

env:
 - FS_BACKEND=ON
 - FS_BACKEND=OFF

matrix:
  exclude:
    - os: osx
      compiler: gcc

addons:
  homebrew:
    packages:
      - cmake
      - boost
      - cppunit
      - hdf5
      - yaml-cpp
    update: true

before_cache:
  - brew cleanup

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

before_install:
  - docker build -f ./dockerfiles/albuild.Dockerfile . -t local/nixio
  - docker run -it -d --name nixbuilder local/nixio
  - if [[ "$CXX" == "g++" ]];
    then
       export CTEST_ARGS=-V;
    else
       export CTEST_ARGS=-VV;
    fi
  - if [ "$CXX" == "g++" ]; then
      docker exec nixbuilder g++ --version;
    else
      docker exec nixbuilder clang --version;
    fi

script:
  - docker exec nixbuilder cmake ..
  - docker exec nixbuilder make
  - docker exec nixbuilder make test

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$FS_BACKEND" == "OFF" ]]; then
      lcov -q --capture --directory . --no-extern --output-file coverage.info;
      bash <(curl -s https://codecov.io/bash) -f coverage.info -Z;
    fi

notifications:
  irc: "chat.freenode.net#gnode"
