language: cpp

sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - kalakris-cmake
      - boost-latest
    packages:
      - libcppunit-dev
      - libboost1.55-all-dev
      - libhdf5-serial-dev
      - valgrind
      - cmake
      - g++-4.8

before_install:
  - if [[ "$CXX" == "g++" ]]; then
      export CTEST_ARGS=-V;
      pip install --user cpp-coveralls;
    else
      export CTEST_ARGS=-VV;
    fi

install:
  - if [[ "$CXX" == "g++" ]]; then
      export CXX="g++-4.8";
      export COMPILER="g++";
      $CXX --version;
    else
      clang --version;
    fi

script:
  - ctest ${CTEST_ARGS} --output-on-failure -S .travis.ctest

after_success:
  - if [[ "$COMPILER" == "g++" ]]; then
      coveralls -b build -E ".*CMakeFiles.*" -e cli -e test -e tmp --gcov gcov-4.8 --gcov-options '\-lp' > /dev/null ;
    fi

notifications:
  irc: "chat.freenode.net#gnode"