language: cpp
env:
  global:
    - CMAKE_BUILD_TYPE=DEBUG
  matrix:
    - COMPILER=g++-4.8
    - COMPILER=clang CXXFLAGS="-stdlib=libstdc++"

before_script:
- mkdir -p build
- cd build
- CXX=${COMPILER} cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..
- cd ..

script:
- cd build
- make
- cd ..

after_success:
- cd build
- ctest -D Experimental
- cd ..

install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo add-apt-repository ppa:gnode/pandora -y
- sudo apt-get update -qq -y
- sudo apt-get install gcc-4.8 g++-4.8 libstdc++-4.8-dev libcppunit-dev libboost-all-dev libhdf5-serial-dev libhdf5-dev libhdf5-7

