language: cpp

sudo: required
dist: xenial

services:
  - docker

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

env:
 - FS_BACKEND=ON
 - FS_BACKEND=OFF

matrix:
  exclude:
    - os: osx
      compiler: gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ];
    then
       export CC=clang;
       export CXX=clang++;
       export GCOV=gcov;
       export CTEST_ARGS=-VV;
    elif [[ "$CXX" == "g++" ]];
    then
       export CC=gcc-8;
       export CXX=g++-8;
       export GCOV=gcov-8
       export CTEST_ARGS=-V;
    else
       export CC=clang-7;
       export CXX=clang++-7;
       export GCOV=gcov-8;
       export CTEST_ARGS=-VV;
    fi

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ];
    then
      ./contrib/make-env.sh /tmp/docker.env;
      docker build -t nix-ub1804 -f ./contrib/Dockerfile-ub1804 .;
      docker run --env-file /tmp/docker.env -d -i -t -v `pwd`:/src --name nix nix-ub1804;
      docker exec nix ${CXX} --version;
    elif [ "$TRAVIS_OS_NAME" == "osx" ];
    then
      brew update;
      brew install cmake boost cppunit hdf5 yaml-cpp;
      brew --env;
    fi

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ];
    then
      docker exec nix ctest ${CTEST_ARGS} --output-on-failure -S .travis.ctest;
    else
      $CXX --version;
      ctest ${CTEST_ARGS} --output-on-failure -S .travis.ctest;
    fi

after_success:
  - if [[ "$TRAVIS_COMPILER" == "gcc" ]];
    then
        docker exec nix coveralls -b build -E ".*CMakeFiles.*" -e cli -e test -e tmp --gcov ${GCOV} --gcov-options '\-lp';
    fi

notifications:
  irc: "chat.freenode.net#gnode"
