var namespacenix =
[
    [ "base", "d8/d63/namespacenix_1_1base.html", "d8/d63/namespacenix_1_1base" ],
    [ "check", "df/d59/namespacenix_1_1check.html", null ],
    [ "util", "d2/db1/namespacenix_1_1util.html", "d2/db1/namespacenix_1_1util" ],
    [ "Block", "d0/d1a/classnix_1_1_block.html", "d0/d1a/classnix_1_1_block" ],
    [ "DataArray", "de/ddd/classnix_1_1_data_array.html", "de/ddd/classnix_1_1_data_array" ],
    [ "DataSet", "d6/d01/classnix_1_1_data_set.html", "d6/d01/classnix_1_1_data_set" ],
    [ "DataView", "de/dc8/classnix_1_1_data_view.html", "de/dc8/classnix_1_1_data_view" ],
    [ "SampledDimension", "d3/de3/classnix_1_1_sampled_dimension.html", "d3/de3/classnix_1_1_sampled_dimension" ],
    [ "SetDimension", "d2/d37/classnix_1_1_set_dimension.html", "d2/d37/classnix_1_1_set_dimension" ],
    [ "RangeDimension", "db/d57/classnix_1_1_range_dimension.html", "db/d57/classnix_1_1_range_dimension" ],
    [ "Dimension", "db/dfb/classnix_1_1_dimension.html", "db/dfb/classnix_1_1_dimension" ],
    [ "OutOfBounds", "d9/d64/classnix_1_1_out_of_bounds.html", "d9/d64/classnix_1_1_out_of_bounds" ],
    [ "InvalidRank", "d7/db1/classnix_1_1_invalid_rank.html", "d7/db1/classnix_1_1_invalid_rank" ],
    [ "UninitializedEntity", "d0/db7/classnix_1_1_uninitialized_entity.html", "d0/db7/classnix_1_1_uninitialized_entity" ],
    [ "EmptyString", "dc/d5d/classnix_1_1_empty_string.html", "dc/d5d/classnix_1_1_empty_string" ],
    [ "DuplicateName", "d5/d04/classnix_1_1_duplicate_name.html", "d5/d04/classnix_1_1_duplicate_name" ],
    [ "InvalidName", "d8/da9/classnix_1_1_invalid_name.html", "d8/da9/classnix_1_1_invalid_name" ],
    [ "UnsortedTicks", "d1/d05/classnix_1_1_unsorted_ticks.html", "d1/d05/classnix_1_1_unsorted_ticks" ],
    [ "InvalidUnit", "d9/df4/classnix_1_1_invalid_unit.html", "d9/df4/classnix_1_1_invalid_unit" ],
    [ "IncompatibleDimensions", "d1/dee/classnix_1_1_incompatible_dimensions.html", "d1/dee/classnix_1_1_incompatible_dimensions" ],
    [ "InvalidDimension", "d9/d7c/classnix_1_1_invalid_dimension.html", "d9/d7c/classnix_1_1_invalid_dimension" ],
    [ "MissingAttr", "d0/df5/classnix_1_1_missing_attr.html", "d0/df5/classnix_1_1_missing_attr" ],
    [ "Feature", "d5/da4/classnix_1_1_feature.html", "d5/da4/classnix_1_1_feature" ],
    [ "File", "d7/d35/classnix_1_1_file.html", "d7/d35/classnix_1_1_file" ],
    [ "Group", "d7/d9d/classnix_1_1_group.html", "d7/d9d/classnix_1_1_group" ],
    [ "MultiTag", "d3/d72/classnix_1_1_multi_tag.html", "d3/d72/classnix_1_1_multi_tag" ],
    [ "NDArray", "d5/d53/classnix_1_1_n_d_array.html", "d5/d53/classnix_1_1_n_d_array" ],
    [ "NDSizeBase", "d3/ddb/classnix_1_1_n_d_size_base.html", "d3/ddb/classnix_1_1_n_d_size_base" ],
    [ "Property", "d7/dde/classnix_1_1_property.html", "d7/dde/classnix_1_1_property" ],
    [ "Section", "d0/db0/classnix_1_1_section.html", "d0/db0/classnix_1_1_section" ],
    [ "Source", "dc/da0/classnix_1_1_source.html", "dc/da0/classnix_1_1_source" ],
    [ "Tag", "d5/dc5/classnix_1_1_tag.html", "d5/dc5/classnix_1_1_tag" ],
    [ "Value", "d9/dfb/classnix_1_1_value.html", "d9/dfb/classnix_1_1_value" ],
    [ "Variant", "db/db3/classnix_1_1_variant.html", "db/db3/classnix_1_1_variant" ]
];