name: CI
on: [push]
jobs:
  build-macos:
    name: Build on macOS
    runs-on: macOS-10.14
    steps:
    - name: Install dependecies
      run: |
        brew update
        brew install cmake boost cppunit hdf5 yaml-cpp
    - name: Install coveralls
      run: |
        pip install --upgrade pip
        pip install --user cpp-coveralls
    - uses: actions/checkout@v1
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DBUILD_FS_BACKEND=OFF ..
        make
        make test
